from tkinter import *

janela = Tk()
janela.configure(background='#B8B4BD')

janela.grid_rowconfigure(0,weight=1)
janela.grid_rowconfigure(1,weight=1)
janela.grid_rowconfigure(2,weight=1)
janela.grid_rowconfigure(3,weight=1)
janela.grid_rowconfigure(4,weight=1)

janela.grid_columnconfigure(0,weight=1)
janela.grid_columnconfigure(1,weight=1)
janela.grid_columnconfigure(2,weight=1)
janela.grid_columnconfigure(3,weight=1)
janela.grid_columnconfigure(4,weight=1)
janela.grid_columnconfigure(5,weight=1)

fr1 = Frame(janela,background='#a7a1ac')
fr2 = Frame(janela,background='#a7a1ac')
fr3 = Frame(janela,background='#a7a1ac')
fr4 = Frame(janela,background='#a7a1ac')

titulo = Label(fr1,text='Cadastro',font='Arial 26 bold italic',bg='#B8B4BD')
blc1 = Label(fr2,font='Arial 20',background='#a7a1ac')

subt= Label(fr2,text='Dados Pessoais',font='Arial 21 italic',bg='#ACA7A1')
blc4 = Label(fr2,font='Arial 20',background='#a7a1ac')
nome = Label(fr2,text='Nome:',font='roman 20 bold',bg='#a7a1ac')
nasc = Label(fr2,text='Nascimento:',font='roman 20 bold',bg='#a7a1ac')
CPF = Label(fr2,text='CPF:',font='roman 20 bold',bg='#a7a1ac')
telefone = Label(fr2,text='Telefone:',font='roman 20 bold',bg='#a7a1ac')
nomeR = Entry(fr2,font='Roman 20',width=25)
nascR = Entry(fr2,font='Roman 20',width=18)
CPFR = Entry(fr2,font='Roman 20')
telefoneR = Entry(fr2,font='Roman 20')
blc2 = Label(fr2,font='Arial 20',background='#a7a1ac')

subt2 = Label(fr3,text='Endereço',font='Arial 21 italic',bg='#ACA7A1')
blc5 = Label(fr3,font='Arial 20',background='#a7a1ac')
rua = Label(fr3,text='Rua:',font='roman 20 bold',bg='#a7a1ac')
bairro = Label(fr3,text='Bairro:',font='roman 20 bold',bg='#a7a1ac')
cidade = Label(fr3,text='Cidade:',font='roman 20 bold',bg='#a7a1ac')
N = Label(fr3,text='N°:',font='roman 20 bold',bg='#a7a1ac')
UF = Label(fr3,text='UF:',font='roman 20 bold',bg='#a7a1ac')
ruaR = Entry(fr3,font='Roman 20')
bairroR = Entry(fr3,font='Roman 20')
cidadeR = Entry(fr3,font='Roman 20')
NR = Entry(fr3,font='Roman 20')
UFR = Entry(fr3,font='Roman 20')
blc3 = Label(fr3,font='Arial 20',background='#a7a1ac')

gravar = Button(fr4,text='Gravar Dados',font='Arial 18')
listar = Button(fr4,text='Listar Dados',font='Arial 18')

fr1.grid()
fr2.grid(sticky=NSEW)
fr3.grid(sticky=NSEW)
fr4.grid()

titulo.grid(row=0,column=1)
blc1.grid(row=1,column=0)

subt.grid(row=0,column=0,columnspan=2)
blc4.grid(row=1,column=0)
nome.grid(row=2,column=0)
nasc.grid(row=2,column=3)
CPF.grid(row=3,column=0)
telefone.grid(row=3,column=3)
nomeR.grid(row=2,column=1)
nascR.grid(row=2,column=4)
CPFR.grid(row=3,column=1)
telefoneR.grid(row=3,column=4)
blc2.grid(row=4,column=0)

subt2.grid(row=0,column=0,columnspan=2)
blc5.grid(row=1,column=0)
rua.grid(row=2,column=0)
bairro.grid(row=3,column=0)
cidade.grid(row=3,column=2)
N.grid(row=2,column=2)
UF.grid(row=3,column=4)
ruaR.grid(row=2,column=1)
bairroR.grid(row=3,column=1)
cidadeR.grid(row=3,column=3)
NR.grid(row=2,column=3)
UFR.grid(row=3,column=5)
blc3.grid(row=4,column=0)

gravar.grid(row=0,column=0)
listar.grid(row=0,column=1)

janela.mainloop()
